# Generated by Django 3.2.3 on 2021-06-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_visualized',
        ),
    ]
