# Generated by Django 3.2.3 on 2021-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0003_notification_is_visualized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_visualized',
            field=models.BooleanField(default=False),
        ),
    ]
