# Generated by Django 3.2.3 on 2021-06-02 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0004_alter_notification_is_visualized'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='upload_date_not',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
            preserve_default=False,
        ),
    ]
