# Generated by Django 3.2.3 on 2021-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0006_auto_20210603_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=True, upload_to='index/files/'),
        ),
    ]
