# Generated by Django 3.2.3 on 2021-06-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0007_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
