# Generated by Django 3.2.3 on 2021-06-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0011_alter_file_is_malware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
