# Generated by Django 3.2.3 on 2021-06-26 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0012_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
            preserve_default=False,
        ),
    ]
