# Generated by Django 3.2.3 on 2021-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0013_auto_20210626_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(default='', verbose_name='date uploaded'),
        ),
    ]
