# Generated by Django 3.2.3 on 2021-06-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0015_alter_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='upload_date_not',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date uploaded'),
        ),
    ]
