# Generated by Django 3.2.3 on 2021-06-28 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0016_alter_notification_upload_date_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='SaveYourServerTFGApp.myuser'),
            preserve_default=False,
        ),
    ]
