# Generated by Django 3.2.3 on 2021-06-28 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SaveYourServerTFGApp', '0017_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='upload_date_not',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
